### ISSUE TITLE
Quick blank page appear when navigating to a different layout in a page using useFetch

### ISSUE THREAD

**Issue by mlbonniec** [nuxt/nuxt#14467]
### Environment

Nuxt CLI v3.0.0-rc.6                                                                                                                            00:26:03
Nuxt project info:                                                                                                                              00:26:05

------------------------------
- Operating System: `Darwin`
- Node Version:     `v18.6.0`
- Nuxt Version:     `3.0.0-rc.6`
- Package Manager:  `npm@8.13.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

This bug is not visible on Sandboxes, because all pages navigation are already displaying quick blank page. Try to clone the reproduction on your computer 😅 
https://codesandbox.io/s/shy-https-f2u380?file=/pages/pages/index.vue

### Describe the bug

When navigating on pages that contains a layout, which also contains a layout, the page display an entire blank page for a quick time.
As you can see on the reproduction link, all my `index.vue` pages are using a `main` layout, who uses the `default` layout.  
Try to navigate from `/pages/other` to `/pages/` or `/` by using links present on pages, and you'll normally see the white page for a few time.

Maybe this issue is not only related to `layouts`, but on my main website, I've got this blank page only on navigating on `/` route, which is the only one implementing nested layouts.

### Additional context

I've checked nuxt/nuxt.js#13832, but unfortunately, my `/` page contains a single root element.  
After more investigation, it's possible that this issue occurs when setting `definePageMeta({ layout: false });` and use `MyNestedLayout` instead as a wrapper component, to allow usage of multiple (named) slots in layout

**Comment by kaname-png** [comment]
Any news on this?
I am facing the same problem and I don't want to have to set the layout for every page i create.
The page has `useFetch` and `ssr`.

https://cdn.discordapp.com/attachments/897487139888062506/1068709899250442280/Naeko_A_friendly_bot_that_will_make_you_happy_Naeko_y_2_paginas_mas_-_Personal__Microsoft_Edge_2023-01-27_19-49-03.mp4

**Comment by kaname-png** [comment]
@danielroe Any progress in this regard? In my humble opinion it is a priority.

**Comment by anedosugov** [comment]
@danielroe still an issue!

**Comment by meixger** [comment]
https://stackblitz.com/edit/nuxt-starter-7dxlug

https://user-images.githubusercontent.com/600424/221414453-8ba08942-f65f-4fc4-b998-3dc83707f91b.mp4

**Comment by lammerfalcon** [comment]
Have the same issue(( please help!

**Comment by meixger** [comment]
> Have the same issue(( please help!

I have abandoned layouts (for now) and now use [nested routes](https://nuxt.com/docs/guide/directory-structure/pages#nested-routes).

**Comment by radek-ziemniewicz** [comment]
The workaround suggested by @scripty-script works for me:
https://stackblitz.com/edit/nuxt-starter-7b3c1a?file=src/app.vue
I did two things:

1. I removed `<NuxtLayout></NuxtLayout>` from `app.vue`.
2. I added `<NuxtLayout></NuxtLayout>` to every single page.

I know it's not perfect, but it works.

**Comment by sawa-ko** [comment]
> The workaround suggested by @scripty-script works:
> https://stackblitz.com/edit/nuxt-starter-7b3c1a?file=src/app.vue
> I did two things:
> 
> 1. I removed `<NuxtLayout></NuxtLayout>` from `app.vue`.
> 2. I added `<NuxtLayout></NuxtLayout>` to every single page.
> 
> I know it could be better, but it works.

This way the layout state will still be maintained between pages?

**Comment by Exquise** [comment]
I am having this same issue in my application although it does not seem to be related to the use of useFetch because I tried it out in a fresh install of Nuxt 3.4.1 and I'm still having the same problem. Doubting myself and my setup of my NuxtLayout's I read the documentation over and over discovering eventually that it was even in the example given on https://nuxt.com/docs/examples/routing/layouts. See attached video for an perfomance trace with the white frames clearly visible.

https://user-images.githubusercontent.com/8432144/232340001-af51c4a9-0bd7-47c3-8040-e78454ee0a8a.mov

**Comment by Exquise** [comment]
The workaround I've applied is similar to the one @radek-ziemniewicz mentioned. I removed `<NuxtLayout>` from app.vue, added a `<NuxtLayout>` to every page, set the name (not autocompleted by the way) on the `<NuxtLayout>` component and used `definePageMeta({ layout: false });`.

A new insight for me was that the flicker even happened between a page with a simple `<NuxtLayout>` (one without a name set and no `definePageMeta({ layout: false });`, which defaults to the default layout) and a page with `<NuxtLayout name="default">`.

I hope this makes sense to someone, if a Sandbox is appreciated I'm happy to provide one. I'm not happy with this solution but the flicker was driving me mad, hope this helps someone out!

**Comment by Exquise** [comment]
> > The workaround suggested by @scripty-script works:
> > https://stackblitz.com/edit/nuxt-starter-7b3c1a?file=src/app.vue
> > I did two things:
> > 
> > 1. I removed `<NuxtLayout></NuxtLayout>` from `app.vue`.
> > 2. I added `<NuxtLayout></NuxtLayout>` to every single page.
> > 
> > I know it could be better, but it works.
> 
> This way the layout state will still be maintained between pages?

No, I don't think so. I think I just figured out that the "solution" that I provided in the previous message causes a re-initialization of the layout, which, off course, is a problem for my application 😢

**Comment by utarwyn** [comment]
Hello @danielroe! This issue is only a "minor bug"? I have the impression that this affects a lot of people, and although the workaround works, it is not a sustainable and simple solution to set up for sites with many pages. Is it possible to schedule a fix? Do you need any help on this? Thanks

**Comment by frasza** [comment]
I also am experiencing that 'white blink' bug @danielroe. I do have `<NuxtLayout>` as many others suggest in app.vue

**Comment by adinvadim** [comment]
I also have the same bug

**Comment by Artem-Schander** [comment]
For me the fixes are not working. Page flickers on every layout change regardless of `<NuxtLayout>` being inside the page component.

**Comment by bitbytebit1** [comment]
Also waiting to see traction on this issue @danielroe?

**Comment by kogratte** [comment]
Facing the same issue, and having headache, but also a workaround.

To me, using the latest version of almost everything (ie, nuxt 3.6), the issue appear while using `a` nodes. As soon as I switched back to an ugly `@click.stop.prevent="navigateTo(item.href)"`, the issue vanished.

I guess this is due to the fact that the whole page is computed, then updated, when using the `a`, but not when using the composable directly.

**Comment by MoterHaker** [comment]
To solve this issue I had to use a separate component as a layout with a slot. The flickering is gone.

**Comment by Krislunde** [comment]
> To solve this issue I had to use a separate component as a layout with a slot. The flickering is gone.

Elaborate, please?

**Comment by Krislunde** [comment]
> To solve this issue I had to use a separate component as a layout with a slot. The flickering is gone.

Elaborate, please @MoterHaker ? I also have `<NuxtLayout>` in `app.js` and this bug is driving me nuts.

**Comment by MoterHaker** [comment]
> > To solve this issue I had to use a separate component as a layout with a slot. The flickering is gone.
> 
> Elaborate, please @MoterHaker ? I also have `<NuxtLayout>` in `app.js` and this bug is driving me nuts.

Just create another component, not in layouts dir but in "components". Say MyLayout.vue with code like this:
```
<template>
<div>
  <div>Some headers, etc</div>
  <slot />
</div>
</template>
```

Then use it in your pages:
```
<template>
<MyLayout>
   <div>
     Here comes content.
  </div>
</MyLayout>
</template>

<script setup>
import MyLayout from "../components/MyLayout"
</script>
```

So just do it Vue way, not Nuxt way.

**Comment by Artem-Schander** [comment]
@MoterHaker 
For me this didn't do the trick. I believe its because of page transitions.

**Comment by Krislunde** [comment]
@MoterHaker trick didn't work for me either. It is entirely plausible that it is related to page transitions as I am using these also. In my particular case, I managed to work around the issue by still having NuxtLayout in app.js - and having default layout apply to all pages - then manually assigning `<NuxtLayout>` to pages that need a nested layout (in this case, account pages with a sidebar). No more flickering when navigating to/from pages with a nested layout. 

Not ideal, as I'd like full use of `<NuxtLayout>` in app.js, but might help someone else.

**Comment by danielroe** [comment]
If you are still experiencing this, would you be able to add a reproduction, please? I'd like to confirm that a potential fix works.

**Comment by meixger** [comment]
> If you are still experiencing this, would you be able to add a reproduction, please? I'd like to confirm that a potential fix works.

Does my [reproduction (nuxt@3.2.2)](https://stackblitz.com/edit/nuxt-starter-7dxlug?file=layouts%2Fdefault.vue) from https://github.com/nuxt/nuxt/issues/14467#issuecomment-1445367125 help?

But with [reproduction (nuxt@3.6.1)](https://stackblitz.com/edit/nuxt-starter-b8ttqj?file=layouts%2Fdefault.vue), i cannot reproduce the flickering any more ...

**Comment by danielroe** [comment]
I think we can mark this as resolved in that case with https://github.com/nuxt/nuxt/pull/21450. If anyone is still experiencing this, please feel open a new issue with a reproduction and I'll take a look. 🙏

**Comment by Krislunde** [comment]
Can confirm, seems to be fixed now!

Thanks @danielroe :)

**Comment by mlbonniec** [comment]
Hi :) I can also confirm. It's now fixed on the code I identified the issue last year!
The navigation is now waiting for the data to be fetched :)

**Comment by znonthedev** [comment]
I got the issue again in the latest Nuxt 3.10.1 version. I had 4 pages and whenever I went from the homepage to other pages the destination page became blank. 
`<template>
    <h1 class="text-2xl font-bold text-gray-800 dark:text-gray-100">Dashboard</h1>
    <Component1Example/>
</template>` 

I fixed the issue by wrapping these inside a div
`
<template>
  <div>
    <h1 class="text-2xl font-bold text-gray-800 dark:text-gray-100">Dashboard</h1>
    <Component1Example/>
  </div>
</template>`

this is my app.vue
`<template>
  <NuxtLoadingIndicator/>
    <NuxtLayout>
      <NuxtPage/>
    </NuxtLayout>
</template>
`

Sharing this here if someone gets into this again, you can try this one

**Comment by Degoya-Studio** [comment]
still not working for me. I'm getting a blank page

**app.vue**

```
<template>
  <NuxtLayout>
    <NuxtPage :transition="{
        name: 'bounce',
        mode: 'out-in'
      }" />
    <Toaster />
    <Toast/>
  </NuxtLayout>
</template>

<style>
.layout-enter-active,
.layout-leave-active {
  transition: all 0.4s;
}
.layout-enter-from,
.layout-leave-to {
  filter: grayscale(1);
}
</style>
```


**main layout**

```
<template>
  <div>
     <slot :loading="loading" name="headerNav"/>
    <slot name="content"/>
  </div>
</template>
```

**index page**

```
<template>
  <NuxtLayout name="main">
      <template #headerNav>
       ...
      </template>
      <template #content>
      ....
      </template>
  </NuxtLayout>
</template>

```

**Comment by frasza** [comment]
> still not working for me. I'm getting a blank page
> 
> **app.vue**
> 
> ```
> <template>
>   <NuxtLayout>
>     <NuxtPage :transition="{
>         name: 'bounce',
>         mode: 'out-in'
>       }" />
>     <Toaster />
>     <Toast/>
>   </NuxtLayout>
> </template>
> 
> <style>
> .layout-enter-active,
> .layout-leave-active {
>   transition: all 0.4s;
> }
> .layout-enter-from,
> .layout-leave-to {
>   filter: grayscale(1);
> }
> </style>
> ```
> 
> **main layout**
> 
> ```
> <template>
>   <div>
>      <slot :loading="loading" name="headerNav"/>
>     <slot name="content"/>
>   </div>
> </template>
> ```
> 
> **index page**
> 
> ```
> <template>
>   <NuxtLayout name="main">
>       <template #headerNav>
>        ...
>       </template>
>       <template #content>
>       ....
>       </template>
>   </NuxtLayout>
> </template>
> ```

did you try to wrap NuxtLayout in empty div?

**Comment by Degoya-Studio** [comment]
> did you try to wrap NuxtLayout in empty div?

Thank you! that worked

**Comment by johanelbg** [comment]
Unfortunately I ran into the same issue

Using Nuxt 3.16.2

I have two layout one default and the other one called 'other' ( which just a div and a slot)

I'm using it on /informations

definePageMeta({
  layout: 'other',
  pageTransition: {
    name: 'slide-up',
    mode: 'out-in'
  }
})

but i still have a white blank page before my data load
If i remove the pageTransition, i dont have any issue
