### ISSUE TITLE
503 Server Unavailable

### ISSUE THREAD

**Issue by agracia-foticos** [nuxt/nuxt#15188]
### Environment

- Operating System: `Linux`
- Node Version:     `v18.7.0`
- Nuxt Version:     `3.0.0-rc.12`
- Nitro Version:    `0.6.0`
- Package Manager:  `npm@8.15.0`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@5.3.5`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.20`, `@nuxtjs/device@3.0.0`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-alpha.3`
- Build Modules:    `-`

### Reproduction

we are crawling our website with screaming frog...

When we have about 1,500 urls tracked, the server crashes and starts throwing 503 errors.

![image](https://user-images.githubusercontent.com/77386602/196644111-09fe56d5-4a39-41c2-947b-c6cf2250299c.png)

And at that moment we try to make a request through the browser and it is already impossible.

You have to stop the server and start it again

![image](https://user-images.githubusercontent.com/77386602/196644330-9caca3e6-ff1b-41a2-82b8-2de54c3a85fe.png)

### Describe the bug

we are crawling our website with screaming frog...

When we have about 1,500 urls tracked, the server crashes and starts throwing 503 errors.

![image](https://user-images.githubusercontent.com/77386602/196644111-09fe56d5-4a39-41c2-947b-c6cf2250299c.png)

And at that moment we try to make a request through the browser and it is already impossible.

You have to stop the server and start it again

![image](https://user-images.githubusercontent.com/77386602/196644330-9caca3e6-ff1b-41a2-82b8-2de54c3a85fe.png)

### Logs

```shell
Error: socket hang up
    at connResetException (node:internal/errors:704:14)
    at Socket.socketOnEnd (node:_http_client:505:23)
    at Socket.emit (node:events:525:35)
    at Socket.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by madebyfabian** [comment]
Hey there! Please do @danielroe a favour and just add a [minimal reproduction](https://nuxt.com/docs/community/reporting-bugs) so we can look into that properly, thank you 🙏🏻💚. It takes only a few minutes for you but really helps. 

Since this seems to be fixed in the RC cycle, I'd suggest closing this, but feel free to reopen. 

1500 Requests are a lot though, I feel like you could optimize this with batching requests.

**Comment by agracia-foticos** [comment]
The error keeps occurring!

When I launch a crawler, in which very frequent requests are made, 500 errors are randomly generated.

I have tried to reproduce it in a stackblitz environment https://stackblitz.com/edit/nuxt-starter-sz58za but it has already confirmed that I cannot launch "screaming frog" in its environment.
https://github.com/stackblitz/webcontainer-core/issues/959#issuecomment-1420317060

With version 3.1.2 the error is as follows
![image](https://user-images.githubusercontent.com/77386602/217199204-d048b706-28b2-43b9-8c6b-a026419bdf62.png)
![image](https://user-images.githubusercontent.com/77386602/217199253-edaab242-0d9f-48d7-affa-9fac977ac6dc.png)



However if I access through the browser it does not throw me any error

![image](https://user-images.githubusercontent.com/77386602/217199495-bf213d68-3d3c-47ca-8a02-423a1837e38d.png)

**Comment by agracia-foticos** [comment]
In case it helps, I changed the links from <NuxtLink to <a and it keeps failing

**Comment by danielroe** [comment]
I understand this keeps occurring but it's impossible for us to investigate without a reproduction. (It's not a problem if you can't reproduce the issue in stackblitz; just provide the code and tell me how to reproduce locally.)

**Comment by amihhs** [comment]
The problem looks like it was caused by nuxt-proxy.
Although it is a bit strange for the agent to have the same address, the same situation can occur.
hi @danielroe， If you can hope that this reproduction can solve this problem. I can't find the root problem🙈. [reproduction](https://github.com/amihhs/503-issue)

**Comment by danielroe** [comment]
I would raise it upstream with `nuxt-proxy` in that case. Or you could try the native proxy support we just released today.

**Comment by amihhs** [comment]
I tried nitro's devProxy and routeRules proxy.

```js
nitro: {
    routeRules: {
      '/api/**': { proxy: 'https://otherHost/api/**' }, // Occasionally 503
      // '/api/**': {proxy: 'http://localhost:3000/api/**'} // Server loop prompt 503
    },
    devProxy: {
      '/api': { 
        // target: 'https://otherHost/api', // normal
        target: 'http://localhost:3000/api', // connect EADDRINUSE
        changeOrigin: true,
      }
    },
  },
```

DevProxy.

There is a problem with the api of the agent's current nuxt (maybe this is not a problem).
![4d70b297d85b0978c1e4f8f8afb99c9](https://user-images.githubusercontent.com/59364234/218019819-2144942b-dbb8-4967-9132-df92a7af98a6.png)

RouteRules proxy.

The interface that proxies other addresses will still appear 503, while the api of the current nuxt will serve.
The 503 error message of the loop will appear on the side.
![d46691dd2c0df39ab6d6f4f78ff2cf5](https://user-images.githubusercontent.com/59364234/218019820-377d3786-b5bf-4b3f-b2ae-c12e2cbb71b1.png)

**Comment by agracia-foticos** [comment]
When i debug with Visual Studio 

![image](https://user-images.githubusercontent.com/77386602/218435569-e4d90db2-0a9c-4242-b7fd-d4cf4d2b066d.png)

![image](https://user-images.githubusercontent.com/77386602/218435623-50f8e338-406e-4958-8cde-252175a137da.png)

![image](https://user-images.githubusercontent.com/77386602/218435812-91024e1c-22ec-4ee7-ab7c-aaafc35243ec.png)

**Comment by agracia-foticos** [comment]
I will try mount a reproduction project  that throws the issue indicated in this post.

we are blocked the development of new website in out business with this issue.

**Comment by agracia-foticos** [comment]
I'm trying mount a reproduction environment, but when i developing it, it throws me this issue:

https://github.com/nuxt/nuxt/issues/19113

Maybe its related and the origin of the error

**Comment by agracia-foticos** [comment]
Here you are!!!

https://stackblitz.com/edit/nuxt-starter-u9cwfg

If i open this url in navigator, runs OK
![image](https://user-images.githubusercontent.com/77386602/219660040-14ddf6eb-05fa-48f0-8728-68c9d0913a4a.png)

Buf if i crawl with screaming frog
![image](https://user-images.githubusercontent.com/77386602/219660191-06b813e5-ab8d-46fc-8535-94a98c0bd9b0.png)

I have random errors and the application breaks!

Thanks for the patience

**Comment by danielroe** [comment]
It looks like this is the issue: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.

**Comment by agracia-foticos** [comment]
> It looks like this is the issue: https://nuxt.com/docs/guide/concepts/auto-imports#using-vue-and-nuxt-composables.
> 
> In your reproduction you are calling `useFetch` in places (like the store actions) where it is not meant to be called.

![image](https://user-images.githubusercontent.com/77386602/220293321-433c8ce7-4245-4555-a3f1-e90ed565ba70.png)

Seems WORK!!! Thanks!!

**Comment by danielroe** [comment]
You're very welcome. Glad we could get to the bottom of this.

**Comment by JokerMartini** [comment]
So what is the solution to this then?

**Comment by mrniamster** [comment]
Any solution to this @danielroe  , still coming in nuxt 3.6.3 - unable to send a reproduction , my muct time is going on just restarting the server to work 

![image](https://github.com/nuxt/nuxt/assets/52563039/311cfd89-5156-4d58-af8e-a9b62e1e844e)

**Comment by danielroe** [comment]
I'm sorry about this. It's an upstream nitro issue and is being investigated/tracked.

**Comment by mrniamster** [comment]
@danielroe  Recently to much disapointed with these 2 issues in the nuxt 3.6.x releases..
1. The routes are not auto-generating for Nuxt static site, 
https://github.com/nuxt/nuxt/issues/13949#issuecomment-1637147930

2. The nitro issue: is causing me to write npm run dev every time,

I hope this gets resolved soon :(

**Comment by pi0** [comment]
Hi. You can keep track of this issue via https://github.com/unjs/nitro/issues/1454. It is something certainly to be resolved ASAP.

**Comment by carbdias** [comment]
Hello, I'm having the same problem here, a lot of 503 of components that exist.
