### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by artmarydotir** [nuxt/nuxt#15738]
### Environment

------------------------------
- Operating System: `Linux`
 - Description:	Ubuntu 20.04.5 LTS
 - Release:	20.04
- Node Version:     `v16.18.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `css`, `ssr`, `app`, `postcss`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

Created an error.vue page [like this](https://nuxt.com/docs/getting-started/error-handling#example)

```
<template>
  <div>
    <div class="container max-w-200">
      <h1>{{ error.message }}</h1>
      There was an error 😱
      <br />
      <button @click="handleError">Clear error</button>
      <br />
      <NuxtLink to="/404"> Trigger another error </NuxtLink>
      <br />
      <NuxtLink to="/"> Navigate home </NuxtLink>
    </div>
  </div>
</template>

<script setup>
const router = useRouter();
const props = defineProps({ error: Object });

if (router.currentRoute.value.fullPath === "/old-slug") {
  await navigateTo("/new-slug", {
    redirectCode: 301,
  });
}

const handleError = () => clearError({ redirect: "/" });
</script>


```

### Describe the bug

When i curl this url :

```
$ curl http://192.168.0.117:3000/old-slug -v
...
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Access-Control-Allow-Origin: *
< location: /new-slug
< content-type: text/html
< server-timing: -;dur=0;desc="Generate"
< date: Wed, 30 Nov 2022 18:25:24 GMT
< connection: close
< content-length: 95
< 
* Closing connection 0
<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/new-slug"></head></html>
```

**everything works correctly except get this error on server:**

```
[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:387:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at Object.errorhandler [as onError] (/nuxt3test/nuxt-app/.nuxt/dev/index.mjs:427:20)
    at Server.toNodeHandle (/nuxt3test/nuxt-app/node_modules/h3/dist/index.mjs:752:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

```

**Comment by danielroe** [comment]
Would someone be able to provide a standalone reproduction? 🙏

**Comment by lukaszflorczak** [comment]
@adriaanvanrossum Do you use `i18n`? I see lang prefix in your urls. We have similar problem in our project. And it looks similar to that issue: https://github.com/nuxt-modules/i18n/issues/1611. My reproduction for `i18n` is here: http://github.com/lukaszflorczak/nuxt-middleware-playground

**Comment by adriaanvanrossum** [comment]
@danielroe here you go: https://stackblitz.com/edit/github-vgyh5u?file=middleware/redirects.global.js


<img width="1566" alt="image" src="https://user-images.githubusercontent.com/1079135/214022104-1ee1998a-becc-4c75-a75b-5a1ebf748a45.png">


@lukaszflorczak, I don't think it's i18n because it happens without it (as well).

**Comment by danielroe** [comment]
@adriaanvanrossum Great. This should be resolved with https://github.com/nuxt/nuxt/pull/18445.

**Comment by adriaanvanrossum** [comment]
That's very fast. Thank you!

**Comment by lukaszflorczak** [comment]
Looks like this solved my problem as well.

**Comment by Developer27149** [comment]
@danielroe Hi~ Can you explain the possible reasons for this error message? Because I upgraded to v3.3.3 and still encountered this problem, thank you very much.

**Comment by videmann** [comment]
same error here

nuxt 3.6.5 + nitro 2.6.0

[nuxt] [request error] [unhandled] [500] Cannot set headers after they are sent to the client
  at new NodeError (node:internal/errors:371:5)  
  at ServerResponse.setHeader (node:_http_outgoing:576:11)  
  at setResponseHeaders (./.output/server/chunks/nitro/node-server.mjs:1:128298)  
  at ./.output/server/chunks/handlers/renderer.mjs:1:4866  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at Object.handler (./.output/server/chunks/nitro/node-server.mjs:1:134475)  
  at Server.<anonymous> (./.output/server/chunks/nitro/node-server.mjs:1:136797)

**Comment by lafllamme** [comment]
still same issue here, internal middleware that should return on fail gives me:

```
nuxt-app  |  ERROR  [nitro] [unhandledRejection] Cannot set headers after they are sent to the client
nuxt-app  | 
nuxt-app  |   at ServerResponse.setHeader (node:_http_outgoing:703:11)
nuxt-app  |   at sendRedirect (node_modules/.pnpm/h3@1.11.1/node_modules/h3/dist/index.mjs:765:18)
nuxt-app  |   at ServerResponse.<anonymous> (server/middleware/handleFail.ts:12:1)
```

**Comment by OhB00** [comment]
Thought I'd share, not awaiting promises caused this for me, check you've not missing any `await`
