### ISSUE TITLE
After nuxt installation npm run dev occurs error

### ISSUE THREAD

**Issue by sadducean** [nuxt/nuxt#19841]
### Environment

Nuxt project info:                                                                                                                                                             17:59:17

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.14.2`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Package Manager:  `yarn@1.22.19`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://stackblitz.com/edit/github-wdaflq-jqcxbf?file=nuxt.config.ts

just follow installation guide on https://nuxt.com/docs/getting-started/installation

and type on terminal npm run dev

### Describe the bug

after npm run dev errors on terminal console:

Nuxi 3.3.1                                                                                                                                                                     17:56:23  
Nuxt 3.3.1 with Nitro 2.3.1                                                                                                                                                    17:56:23
                                                                                                                                                                               17:56:24
  > Local:    http://localhost:3000/ 
  > Network:  http://172.27.160.1:3000/                                                                                                                                        17:56:23  
  > Network:  http://172.31.16.1:3000/
  > Network:  http://192.168.0.125:3000/

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/ofetch/dist/index.mjs?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/ofetch/dist/index.mjs?v=babcfa76) in C:/codes/vscode-workspace/node_modules/nuxt/dist/app/entry.js. Does the file exist?

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/ufo/dist/index.mjs?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/ufo/dist/index.mjs?v=babcfa76) in virtual:nuxt:C:/codes/vscode-workspace/nuxt-test/.nuxt/paths.mjs. Does the file exist?

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/nuxt/dist/head/runtime/plugins/unhead.js?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/nuxt/dist/head/runtime/plugins/unhead.js?v=babcfa76) in virtual:nuxt:C:/codes/vscode-workspace/nuxt-test/.nuxt/plugins/client.mjs. Does the file exist?

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/nuxt/dist/head/runtime/plugins/vueuse-head-polyfill.js?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/nuxt/dist/head/runtime/plugins/vueuse-head-polyfill.js?v=babcfa76) in virtual:nuxt:C:/codes/vscode-workspace/nuxt-test/.nuxt/plugins/client.mjs. Does the file exist?

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/ufo/dist/index.mjs?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/ufo/dist/index.mjs?v=babcfa76) in virtual:nuxt:C:/codes/vscode-workspace/nuxt-test/.nuxt/paths.mjs. Does the file exist?

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/h3/dist/index.mjs?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/h3/dist/index.mjs?v=babcfa76) in C:/codes/vscode-workspace/node_modules/nuxt/dist/app/plugins/router.js. Does the file exist?

                                                                                                                                                                               17:56:25

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/h3/dist/index.mjs?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/h3/dist/index.mjs?v=babcfa76) in C:/codes/vscode-workspace/node_modules/nuxt/dist/app/plugins/router.js. Does the file exist? (x2)

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/ufo/dist/index.mjs?v=babcfa76 (resolved id: C:/codes/vscode-workspace/node_modules/ufo/dist/index.mjs?v=babcfa76) in virtual:nuxt:C:/codes/vscode-workspace/nuxt-test/.nuxt/paths.mjs. Does the file exist?

 ERROR  Failed to load url /@fs/C:/codes/vscode-workspace/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue (resolved id: C:/codes/vscode-workspace/node_modules/@nuxt/ui-templates/dist/templates/welcome.vue) in C:/codes/vscode-workspace/nuxt-test/app.vue. Does the file exist?

**Comment by danielroe** [comment]
Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

**Comment by sadducean** [comment]
> 



> Would you provide a [reproduction](https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction)? 🙏

i updated the content 
reproduction url is : https://nuxt.com/docs/community/reporting-bugs/#create-a-minimal-reproduction) https://stackblitz.com/edit/github-wdaflq-jqcxbf?file=nuxt.config.ts

**Comment by maxdzin** [comment]
Hello guys,
I have the same issue with a fresh install of the Nuxt v3.3.1 app:
```bash
ERROR  Failed to load url /@fs/node_modules/ofetch/dist/index.mjs?v=fa5b3152 (resolved id: /node_modules/ofetch/dist/index.mjs?v=fa5b3152) in /node_modules/nuxt/dist/app/entry.js. Does the file exist?
```

**Comment by JulienChampagnol** [comment]
Same here, I'm on Nuxt 3.4.2

I get the same error, as well as this one:

`
The request url "node_modules/ofetch/dist/index.mjs" is outside of Vite serving allow list.
Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.
`

Seems to be a Vite issue...

**Comment by maxdzin** [comment]
Since updating to Nuxt `3.4.2` and running `npx nuxt upgrade --force` it works without errors.

**Comment by sdr0x07b6** [comment]
I was also having a very hard time working with the same error message.

But in my case, I had tried the PWA module the day before and it was not working properly, so I gave up using it and deleted the project. I had forgotten that such a thing had happened, but the reason was that the Service Worker at that time was still always waiting at port3000 in the browser and was interfering with the port of the new working project.

I opened Developer Tools and deleted the Service Worker registration and the problem was solved.

**Comment by sgaconsultores** [comment]
I'm having the same issue, my project was working fine, came back from holidays and now I have all this errors when running npm run dev :( anyone found a solution?

**Comment by Utitofon-Udoekong** [comment]
This still happens on nuxt 3.5.1. I haven't found a fix yet.

**Comment by danielroe** [comment]
I cannot reproduce this when following the below steps:

```sh
npx nuxi@latest init nuxt-test
cd nuxt-test
yarn
yarn dev
```

(I'm using yarn here as that is what mentioned as your package manager in the initial issue.)

**Comment by lpfy** [comment]
> I cannot reproduce this when following the below steps:
> 
> ```shell
> npx nuxi@latest init nuxt-test
> cd nuxt-test
> yarn
> yarn dev
> ```
> 
> (I'm using yarn here as that is what mentioned as your package manager in the initial issue.)

After upgrading to 3.5.2, the error message changed to say yaml package has problem, could not find the directive.js. delete lock file and node_modules folder, re-run yarn install, same error. I have to copy all files to another folder (excluding lock file and node_modules), and re-run yarn install, everything becomes fine

**Comment by danielroe** [comment]
Okay, it sounds like an issue outside of Nuxt. I'll close, but please let me know if it reoccurs and can be reproduced.

**Comment by fabianwohlfart** [comment]
I have no idea why this is happening, but when i do `git init` and afterwards `yarn dev` it throws me those errors. If I `sudo rm -r .git` again it works fine again?!

It's also only with `node_modules` and shows me this `Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.` when I try to open it on `localhost:3000`

**Comment by fabianwohlfart** [comment]
I could solve it by setting

### nuxt.config.js
```js

  vite: {
    server: {
      fs: {
        strict: false
      }
    }
  }

```

**Comment by joelawm** [comment]
> I could solve it by setting
> 
> ### nuxt.config.js
> ```js
>   vite: {
>     server: {
>       fs: {
>         strict: false
>       }
>     }
>   }
> ```

This worked for me as well, I was having issues between my Mac and Windows machine and this fixed that issue. Before the only way I could seem to get the error to go away was transplanting the code into a known working blank nuxt app. Then as soon as I push the code to git it work break again. This is also with me ignoring .lock, modules and .nuxt folders/files. Vite was definitely causing the issue

**Comment by samk-dev** [comment]
> I could solve it by setting
> 
> ### nuxt.config.js
> ```js
>   vite: {
>     server: {
>       fs: {
>         strict: false
>       }
>     }
>   }
> ```

This is also worked for me, on mac m1, linux debian bookworm x86/amd64 and windows running on parallels all of them use the same packages. The weird things is in my package.json says I have nuxt `3.6.2` and using `npx nuxi@latest info` it says i have `3.6.0`

- Operating System: Darwin
- Node Version:     v18.16.1
- Nuxt Version:     3.6.0
- Nitro Version:    2.5.1
- Package Manager:  pnpm@8.6.7
- Builder:          vite
- User Config:      devtools, app, modules, css, runtimeConfig, routeRules, colorMode, i18n, vite
- Runtime Modules:  @nuxtjs/i18n@8.0.0-beta.12, @nuxtjs/color-mode@3.3.0, @vueuse/nuxt@10.2.1

**Comment by songjianet** [comment]
> I was also having a very hard time working with the same error message.
> 
> But in my case, I had tried the PWA module the day before and it was not working properly, so I gave up using it and deleted the project. I had forgotten that such a thing had happened, but the reason was that the Service Worker at that time was still always waiting at port3000 in the browser and was interfering with the port of the new working project.
> 
> I opened Developer Tools and deleted the Service Worker registration and the problem was solved.

I also did the same operation and this problem occurred. How did you solve this problem through the developer tools? Can you provide some steps?

**Comment by sdr0x07b6** [comment]
@songjianet Do you see anything here? I don't have anything registered right now, so I can't explain exactly what operation I need to do to delete it.

![Screenshot - 2023-10-25 16 36 10](https://github.com/nuxt/nuxt/assets/1102138/37d98ee4-8a9a-4768-a722-026a77c37745)

**Comment by dlyqs** [comment]
> I could solve it by setting
> 
> ### nuxt.config.js
> ```js
>   vite: {
>     server: {
>       fs: {
>         strict: false
>       }
>     }
>   }
> ```

It worked! thank you!

**Comment by geniy9** [comment]
> ```js
> vite: {
>     server: {
>       fs: {
>         strict: false
>       }
>     }
>   }
> ```
![2024-04-25_143922](https://github.com/nuxt/nuxt/assets/38286972/0f062060-4e01-426b-b1ad-fbeadde69f15)

In a previous project, I made a PWA application and the service worker was installed and launched on localhost:3000
After stopping the service worker, everything worked as it should...
Thank you!

**Comment by avinmaster** [comment]
Same here, just disable unnecessary service worker:
![image](https://github.com/nuxt/nuxt/assets/90766641/5be98c82-1561-417e-8f79-eb8b0b74a7e4)

**Comment by xygodcyx** [comment]
## before:
![image](https://github.com/user-attachments/assets/9c907263-66ee-423f-9726-9930f962765a)
## after:
![image](https://github.com/user-attachments/assets/f26c6a6c-8a1d-435d-80d1-99142b691075)
