### ISSUE TITLE
Dependencies from layers/modules break in 3.7.x!

### ISSUE THREAD

**Issue by peteromano** [nuxt/nuxt#23077]
### Environment

Latest pnpm

Working directory: /home/projects/nuxt-starter-qea1r5/packages/apps/my-app                                                                                                              5:21:21 PM
Nuxt project info:                                                                                                                                                                      5:21:21 PM

------------------------------
- Operating System: Linux
- Node Version:     v16.20.0
- Nuxt Version:     3.7.1
- CLI Version:      3.8.0
- Nitro Version:    2.6.2
- Package Manager:  npm@9.4.2
- Builder:          -
- User Config:      extends
- Runtime Modules:  -
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                                             5:21:21 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Reproduction

https://stackblitz.com/edit/nuxt-starter-qea1r5

### Describe the bug

Using a pnpm monorepo, layers and/or modules from filesystem workspace, which have dependencies, no longer build correctly after upgrading to 3.7.1, in both dev and production build.

Since trying ^3.7.0, i get this error now:

`[nuxt] Could not resolve id yup /workspace/packages/my-app/index.html`

1) i have a module which includes a dependency (yup)
2) And a component in the module uses this dependency (yup)
3) module auto-imports the component.
4) my-app uses the module from the pnpm workspace
5) now getting this error on my-app startup (pnpm dev)

This worked fine in 3.6.5, and is a breaking change

i moved from using a module to using a layer:

1) Layer has dep for yup
2) Layer Component imports yup
3) App extends layer
4) App uses layer component
5) [nuxt] Could not resolve id yup /workspace/packages/my-app/index.html

Only works if i install yup directly in my-app (which is not acceptable)

### Additional context

![image](https://github.com/nuxt/nuxt/assets/392387/a2865d07-e16b-49dd-9882-d4b901f06b81)

**Comment by peteromano** [comment]
Apparently while writing this up, it looks like a Nitro 2.6.3 update fixes the issue (with the vue dependency warning); will continue testing.

Screenshot shows Nitro 2.6.2, running live stackblitz with 2.6.3 works now.

**Comment by peteromano** [comment]
@danielroe Ok, I ran a more extensive test.. 

`npm_config_shared_workspace_lockfile=false` is what is breaking now. With only a workspace lock file, things seem to work fine.

But I need each app/layer/module in the monorepo to have its own lock file (which worked in 3.6.5).

Can this be fixed, or do I have no choice but to use a shared lock file??

**Comment by peteromano** [comment]
Hey @danielroe @pi0 Any eyes/traction/triage on this issue? It's extremely important and regression issue for our project.

**Comment by danielroe** [comment]
It's unlikely to have been fixed in v3.7.3.

**Comment by peteromano** [comment]
> It's unlikely to have been fixed in v3.7.3.

Umm....... I just tried, looks like 3.7.3, and unless something weird with my setup, it actually looks to be working!

Will keep you posted!

**Comment by danielroe** [comment]
Oh.... well, great! 🙌

**Comment by peteromano** [comment]
My layer is still on 3.6.5, so ill upgrade that and Ill remove node_modules and do a full re-install etc. to be sure.

**Comment by peteromano** [comment]
@danielroe Sorry for false positive, this is still an issue :/

**Comment by peteromano** [comment]
Can this please get planned for next patch release? It's driving me absolutely crazy; completely kills any value to that pnpm configuration. It's particularly a greater concern for us Docker/container users with monorepo..

**Comment by danielroe** [comment]
I can't reproduce this, so I'm closing. If this is still present, let me know 🙏
