### ISSUE TITLE
Since 3.8.1: "✨ optimized dependencies changed. reloading" keeps showing up repeatedly, forcing me to include all my dependencies in vite.optimizeDeps.include[]

### ISSUE THREAD

**Issue by TimGuendel** [nuxt/nuxt#25101]
### Environment

```
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     3.8.2
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  yarn@3.6.4
- Builder:          -
- User Config:      telemetry, experimental, devtools, components, app, nitro, imports, vite, css, modules, pinia, image, proxy, runtimeConfig
- Runtime Modules:  @vueuse/nuxt@10.7.0, @pinia/nuxt@0.5.1, nuxt-jsonld@2.0.8, @nuxt-alt/proxy@2.4.9, @nuxt/image@1.1.0
- Build Modules:    -
------------------------------
```

### Reproduction

Does not work on Stackblitz 🤔

### Describe the bug

Unless I add all my dependencies to, this is what the nitro console looks like after starting my server:

```
Nuxt 3.8.2 with Nitro 2.8.1                                                                 16:03:01
                                                                                            16:03:01
  ➜ Local:    http://127.0.0.1:3000/
  ➜ Network:  use --host to expose

  ➜ DevTools: press Shift + Alt + D in the browser (v1.0.6)                                 16:03:03

✔ Nitro built in 5689 ms                                                             nitro 16:03:16
ℹ Vite server warmed up in 11683ms                                                         16:03:17
ℹ Vite client warmed up in 12525ms                                                         16:03:17

ℹ ✨ new dependencies optimized: uuid                                                      16:06:47
ℹ ✨ optimized dependencies changed. reloading                                             16:06:47
ℹ ✨ new dependencies optimized: zxcvbn-typescript                                         16:06:59
ℹ ✨ optimized dependencies changed. reloading                                             16:06:59
ℹ ✨ new dependencies optimized: @unhead/vue, xss                                          16:07:26
ℹ ✨ optimized dependencies changed. reloading                                             16:07:26
[16:07:47] ℹ ✨ new dependencies optimized: just-clone, fuse.js, @splidejs/splide, @splidejs/splide-extension-intersection, @splidejs/splide-extension-auto-scroll, highcharts/modules/accessibility, highcharts, highcharts/highcharts-more.js
ℹ ✨ optimized dependencies changed. reloading                                             16:07:47
ℹ ✨ new dependencies optimized: highcharts/highmaps                                       16:10:33
ℹ ✨ optimized dependencies changed. reloading                                             16:10:33
```

This can't be how it is supposed to work, is it? 🤔

**Comment by manniL** [comment]
This is fixed in 3.9.0

**Comment by alexblunck** [comment]
This issue seems to have returned for me when upgrading from 3.9.0 to 3.9.1

**Comment by manniL** [comment]
@alexblunck can you provide a reproduction?

**Comment by TimGuendel** [comment]
I am still experiencing this  with 3.10.3, but I noticed this only happens on Windows 🤔

**Comment by fabkho** [comment]
@TimGuendel Yep, this is back since updating to 3.10.3. This version breaks my whole project.

**Comment by manniL** [comment]
@fabkho @TimGuendel New issue + repro please - feel free to link this one there then!

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/nuxt/issues/24196
