### ISSUE TITLE
Hydration mismatch for `useId`

### ISSUE THREAD

**Issue by apinrdw** [nuxt/nuxt#25755]
### Environment

- Operating System: Darwin
- Node Version:     v18.17.1
- Nuxt Version:     3.10.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  npm@9.6.7
- Builder:          -
- User Config:      nitro, devtools, experimental, runtimeConfig, components, app, css, modules, shadcn, tailwindcss, image, imports, build
- Runtime Modules:  nuxt-headlessui@1.1.5, nuxt-icon@0.5.0, @pinia/nuxt@0.5.1, @nuxt/image@1.3.0, @sidebase/nuxt-pdf@0.1.2, @nuxtjs/tailwindcss@6.11.4, shadcn-nuxt@0.8.7
- Build Modules:    -

### Reproduction

![Screenshot 2024-02-13 at 01 33 16](https://github.com/nuxt/nuxt/assets/4516973/d115889c-6bac-47d6-bc56-536466b652c9)

### Describe the bug

I got this warn when fully reload the page that use `useId` composable.

**Comment by daniluk4000** [comment]
I've had that in my project when using client-only and fallback inside of it (needed to render empty input). Fixed by removing client-only and by relying on hydration end.

**Comment by gangsthub** [comment]
I have a reproduction link here: https://stackblitz.com/edit/github-rq89e8?file=app.vue,components%2FTestId.vue

This way you don't get the hydration mismatch warning, but you still get the warning added [here](https://github.com/nuxt/nuxt/pull/25616)

```
[nuxt] `useId` is not compatible with components that have `inheritAttrs: false`.
```

**Comment by danielroe** [comment]
We need the ability to v-bind attrs to the root element as `useId` needs to access them when it hydrates.

**Comment by TheDutchCoder** [comment]
> We need the ability to v-bind attrs to the root element as `useId` needs to access them when it hydrates.

Why do you need them on the root element?

It's not uncommon to have custom form elements that have a wrapper div with input/label nested inside where you need the attrs to be bound to the input.

And even then, the attributes are still available (just not on the root element), no?

**Comment by danielroe** [comment]
> Why do you need them on the root element?

It is because of the mechanics of how we ensure a stable ID that matches between server and client. Of course there are other locations they could be stored, but how can the composable 'know' where to access them?

**Comment by jd1378** [comment]
> how can the composable 'know' where to access them?

maybe we can pass a `ref` of the element we use it on as an optional argument to the composable ?

**Comment by gregdev00** [comment]
I believe it's because of how the useId composable was implemented, it had different separators. It is fixed in this [commit](https://github.com/nuxt/nuxt/commit/15a4a080acb441a5978c7d08f683c27f46f09c06).

**Comment by gregdev00** [comment]
It is still producing this issue as of nuxt 3.11.0, the problem is that the return statement at the bottom of the _packages/nuxt/src/app/composables/id.ts_ file has a different separator than the one specified at the top in a constant 

```
const SEPARATOR = '-'
.
.
.
// this line needs to be changed to use SEPARATOR instead of the hardcoded _ character
return key + '_' + nuxtApp._id++ 
```

@manniL can you fix this as well please?

**Comment by manniL** [comment]
@gregdev00 no, see https://github.com/nuxt/nuxt/pull/26315

**Comment by madebyfabian** [comment]
Can this be closed then?

**Comment by codeflorist** [comment]
I'm still getting this error in various components (not all):

``` 
  - rendered on server: id="nnOfIU4QIk8-0"
  - expected on client: id="nnOfIU4QIk8_0"
```

There still seem to be cases, where a different seperator character used (`-` vs `_ `).

I think it happens in dynamically loaded components.

**Comment by khaledOghli** [comment]
`
useId` might not work correctly with components that have `inheritAttrs: false`.
`
What is the best way to use useId with inheritAttrs: false !?
