### ISSUE TITLE
HMR WebSocket "Invalid frame header" error causing continuous page reloads after setting app.baseURL

### ISSUE THREAD

**Issue by Wulawa** [nuxt/nuxt#26396]
### Environment

- Operating System: Darwin
- Node Version:     v21.5.0
- Nuxt Version:     3.11.1
- CLI Version:      3.11.0
- Nitro Version:    2.9.4
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      app, devtools
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

1. Set `app.baseURL` in `nuxt.config.js`.
2. Run the application in development mode.
3. Visit the service address.
4. See error in the console and the page continuously reloads.

### Describe the bug

In Nuxt 3, after setting the `baseURL`, the Hot Module Replacement (HMR) WebSocket throws an "Invalid frame header" error, causing the page to continuously reload in development mode.

**Comment by szadave** [comment]
I think, this is related: https://github.com/nuxt/nuxt/issues/23832#issuecomment-2007498167

**Comment by danielroe** [comment]
I believe this has been resolved in nuxt v3.11.1 via https://github.com/nuxt/cli/pull/370.

**Comment by cdwmhcc** [comment]
> I believe this has been resolved in nuxt v3.11.1 via [nuxt/cli#370](https://github.com/nuxt/cli/pull/370).

Not resolved

**Comment by Wulawa** [comment]
> > I believe this has been resolved in nuxt v3.11.1 via [nuxt/cli#370](https://github.com/nuxt/cli/pull/370).
> 
> Not resolved

This is fine. You’ll need to manually install Nuxi because Nuxt’s dependency hasn’t been updated.

**Comment by cdwmhcc** [comment]
> manually install Nuxi

```
"devDependencies": {
    "@nuxt/image": "^1.4.0",
    "@nuxtjs/i18n": "^8.2.0",
    "nuxi": "^3.11.1",
    "nuxt": "^3.11.1",
    "prettier": "^3.2.5",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
```

```
 ERROR  [unhandledRejection] read ECONNRESET                                                                  11:03:41

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)


 ERROR  [unhandledRejection] read ECONNRESET                                                                  11:03:43

  at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
```

**Comment by abarke** [comment]
I'm still having issues with this after upgrading. Really frustrating. First `npx nuxi@latest upgrade` did not want to upgrade to `nuxt@3.11.2` so I manually upgraded using `pnpm up nuxt --latest` and now this issue 😓

**Electron**
<img width="348" alt="image" src="https://github.com/nuxt/nuxt/assets/34715541/b8e971f0-7bb3-4fec-886d-a2230a864774">

**CLI**
<img width="541" alt="image" src="https://github.com/nuxt/nuxt/assets/34715541/12b961a1-4459-47a1-93ef-bf915e9dc291">


**pnpm nuxi info**
```
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.5
- Builder:          -
- User Config:      ssr, css, modules, ionic, vite, nitro
- Runtime Modules:  @nuxtjs/ionic@0.13.1, nuxt-electron@0.7.0
- Build Modules:    -
------------------------------
```

**Comment by qyd159** [comment]
this problem is not solved，i am also stucking
