### ISSUE TITLE
Pages get duplicated when using Google Translate

### ISSUE THREAD

**Issue by LeanderD** [nuxt/nuxt#26549]
### Environment

- Operating System: `Darwin`
- Node Version:     `v21.7.0`
- Nuxt Version:     `3.11.1`
- CLI Version:      `3.11.1`
- Nitro Version:    `2.9.5`
- Package Manager:  `pnpm@8.15.4`
- Builder:          `-`
- User Config:      `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://nuxt-com.translate.goog/?_x_tr_sl=en&_x_tr_tl=fr&_x_tr_hl=nl&_x_tr_pto=wapp

### Describe the bug

For a site I'm creating I'm using Google Translate to translate the site.
(No libraries or anything, just using the link you get from https://translate.google.com when you enter a URL)

Unfortunately, every page gets duplicated. 
![nuxt_google-translate_duplication](https://github.com/nuxt/nuxt/assets/12776247/35a5a948-de9f-46c8-9f1e-e02e03c2f8dd)

At first, I thought it was something I was doing wrong, but then I tried it with a clean Nuxt project. I did not change anything, just generated the project and uploaded it to my server.

As you can see in the screenshot the page gets duplicated.
Then I tried the same on nuxt.com and that also gets duplicated.

I tried searching the GitHub issues, but could not find anything.

**Comment by ChaDevCN** [comment]
Currently, I am facing the same problem as you

**Comment by mlbonniec** [comment]
Hi, I've the same duplication issue with Cloudflare Pages.
But, only on a particular domain.

I've only one Cloudflare Page (CF)

* Domain A is pointing to the CF Page, there is the duplication
* Domain B is pointing to the **same** CF Page, there is **no** duplication

However, Domain A or Domain B translated by Google are duplicated 👀
This is very weird.

> [!NOTE]
> All Cloudflare caches, browser caches etc. have been cleared, and the issue is still present.

**Comment by danielroe** [comment]
This is likely a hydration issue caused by using Google Translate and root nodes. Would you provide a minimal reproduction? 🙏

**Comment by mlbonniec** [comment]
Here's a very minimal reproduction. Only a title explaining the issue.  
https://github.com/mlbonniec/nuxt-26549-reproduction

Previews from Stackblitz can't be translated, so I deployed the reproduction into a Cloudflare Pages.

* Here the [original page](https://nuxt-26549-reproduction.pages.dev/)
* Here the [translated page](https://nuxt--26549--reproduction-pages-dev.translate.goog/?_x_tr_sl=auto&_x_tr_tl=fr&_x_tr_hl=fr&_x_tr_pto=wapp&_x_tr_hist=true)

**Comment by unitythemaker** [comment]
**If you use Cloudflare and have the same issue:**

I experienced a similar issue, but it wasn't due to Google Translate—it was caused by Cloudflare. Disabling Cloudflare's Auto Minify in the ``Speed > Optimization > Content`` section resolved the problem for me.

**Comment by byt3sage** [comment]
I've noticed this happens seemingly on most Nuxt websites... even the Nuxt website itself...

https://nuxt-com.translate.goog/?_x_tr_sl=auto&_x_tr_tl=es&_x_tr_hl=en-US&_x_tr_pto=wapp

@danielroe before I start digging into this further, is there anything your aware of that will point me in the right direction?

**Comment by TaedeM** [comment]
As of April 2026, I am still able to replicate this behaviour. Since it's also on official Nuxt websites, it doesn't appear to be project specific. I tried both nuxt.com and nuxt.studio, both pages are duplicated. 

Vue's official website does not show this behavior, leading me to believe it's a Nuxt-specific rendering or hydration issue. 

Would be great to know if this is still considered a Nuxt issue or perhaps a limitation caused by the way Google Translate rewrites the DOM.

**Comment by emmapaul357-afk** [comment]
Thank you for the update on this issue. I can also confirm that this
behavior is still reproducible as of April 2026 across various Nuxt sites,
including nuxt.com and nuxt.studio.

**Comment by Mateleo** [comment]
I checked many repos, this is the well-known conflict between virtual-DOM frameworks and Google Translate rather than a Nuxt-specific bug we can fix:


- Google Translate rewrites the page by replacing text nodes with `<font>` wrapper elements. Vue still holds references to the original (now-detached) nodes, so its next patch mis-computes fragment boundaries and re-appends the subtree, which surfaces here as the whole page being duplicated.
- Vue core has considered this expected behavior and won't fix it upstream (see vuejs/vue#9160), and React reached the same conclusion (facebook/react#11538). There's no framework-level fix we can build on, and Nuxt can't make third-party DOM mutation safe in general.

Recommended mitigations (from what I have seen):
- Opt the app out of translation: `<html translate="no">` or `<meta name="google" content="notranslate">`
- Wrap dynamic/conditional text in a stable element (e.g. `<span>`) so the `<font>` insertion stays inside a Vue-owned element
- Prefer single root nodes in your `layouts/components`

Also note that some "duplication" reports in this thread turned out to be `Cloudflare Auto Minify` rather than Google Translate.

At the end of the day, I think we can safely close the issue.
@danielroe

**Comment by danielroe** [comment]
nuxtathon closed @Mateleo
