### ISSUE TITLE
HMR with docker and apache proxy

### ISSUE THREAD

**Issue by fouteox** [nuxt/nuxt#27558]
### Environment

- Operating System: Linux
- Node Version:     v22.3.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.8.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    

### Reproduction

Complicated to produce a reproduction because it happens with docker.

### Describe the bug

When updating to version 3.12.1, HMR no longer works.

Here is my docker development environment:

An Apache proxy container in https with self-signed certificates

A node container with nuxt

Here is my nuxt.config file:

```js
  vite: {
    server: {
      hmr: {
        port: 443,
      },
    },
  },
```

Worked great in version 3.11.

Now the error message in console browser:

```log
[vite] failed to connect to websocket (SecurityError: The operation is insecure.).
```

Performing a clean install from Nuxt 3.11 and 3.10 causes the same error.

If I revert my package-lock.json file with version 3.11, everything works again. This makes me think that it is a Nuxt dependency which causes problems, probably vite. But I see there were changes to the hmr in version 3.12 so that may also be the reason.

**Comment by danielroe** [comment]
Would you ensure you're using the latest version of `nuxi`?

**Comment by fouteox** [comment]
Yes, I have the latest version of nuxi:

3.12.0

Ok, I deleted vite.server.hmr and port 443, but I got the same error.

I also tried adding vite.server.hmr.protocol = wss, same error

The strange thing is that it worked before updating to 3.12

I access nuxt via https://example.test (configured in /etc/hosts file).

Then apache proxy redirects traffic to my node container.
It listens for ws connections and redirects them to the node:3000 container

I also tried listening for wss requests in the apache config, but still no.

**Comment by martinszeltins** [comment]
> Would you ensure you're using the latest version of `nuxi`?
> 
> Also, you shouldn't configure `vite.server.hmr`. Nuxt configures Vite HMR to be through the same port as the dev server.

I think you do need to configure hmr port when using Docker, at least that's what I do in my project

```ts
server: {
    hmr: {
        clientPort: (process?.env?.NUXT_PUBLIC_RUNNING_IN_DOCKER === 'false') ? 3000 : 17365
    },
},
```

**Comment by igorgusarov** [comment]
I have the same issue, but using nginx. I'm using Nuxt on port 3010 and nginx as a proxy for https. It was working fine until upgrading to Nuxt 3.12. Nuxt 3.12.1 has the same issue for me.

My config:
```export default defineNuxtConfig({
    // ...
    vite: {
        server: {
            hmr: {
                protocol: 'wss',
                clientPort: 443,
                path: 'hmr/',
            },
        },
    },
    // ...
})```

I tried using it without this config, but got the same issue, just with a different port.

The error I'm getting in Safari:
```[blocked] The page at https://my_domain/my_path/ was not allowed to run insecure content from ws://my_domain:443/app/hmr/.```

As you can see, it tries to use `ws://` instead of `wss://`

- Operating System: Darwin
- Node Version:     v20.11.0
- Nuxt Version:     3.12.1
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.3.0
- Builder:          -
- User Config:      nitro, runtimeConfig, modules, typescript, components, app, security, routeRules, devServer, imports, colorMode, build, css, vite, vue, experimental
- Runtime Modules:  nuxt-security@1.4.3, @nuxtjs/color-mode@3.4.1, @pinia/nuxt@0.5.1, nuxt-scheduler@0.1.9
- Build Modules:    -

**Comment by igorgusarov** [comment]
FYI: when I manually hardcoded `wss://` as protocol in the vite package in setupWebSocket function, everything started working as expected. This makes me think that it's a nuxt/vite configuration issue.

**Comment by slavanossar** [comment]
Also experiencing this issue and that `vite` ignores the `vite.hmr` config and still uses `ws://`. Downgrading `nuxt` doesn't seem to fix the issue, possibly related to some other dependency?

**Comment by fouteox** [comment]
> FYI: when I manually hardcoded `wss://` as protocol in the vite package in setupWebSocket function, everything started working as expected. This makes me think that it's a nuxt/vite configuration issue.

Yes, change at node_modules/vite/dist/client/client.mjs line 507 protocal hard coded "wss" work for me too.

**Comment by hendrikheil** [comment]
I'm not entirely sure which PR introduced it (I think either https://github.com/nuxt/cli/pull/420 or possibly https://github.com/nuxt/nuxt/pull/27326), but there is a quick workaround available until this is resolved properly:

Just add the following hook code to your nuxt.config.ts.

```
  hooks: {
    'vite:extendConfig': (config) => {
      if (typeof config.server!.hmr === 'object') {
        config.server!.hmr.protocol = 'wss';
      }
    },
  },
```

**Comment by babalugats76** [comment]
Really appreciate this workaround and for sharing.  This took me a couple of hours to figure out.  Stabling this and the documentation around changes, how they affect reverse-proxy configs, etc., is hopefully, a priority.

Until such time as this gets figured out...for me:

nuxt.config.js

```javascript
vite: { // @see https://github.com/nuxt/nuxt/issues/27558
    server: {
      hmr: {
        protocol: "wss",
        clientPort: 443,
        path: "hmr/",
      },
    },
  },
  hooks: { // @see https://github.com/nuxt/nuxt/issues/27558
    'vite:extendConfig': (config) => {
      if (typeof config.server.hmr === 'object') {
        config.server.hmr.protocol = 'wss';
        config.server.hmr.clientPort = 443;
        config.server.hmr.path = "hmr/";
      }
    },
  },
```

nginx.conf (relevant snippets)

```javascript
upstream tres_rios_app_upstream {
  server app:3000;
  keepalive 64;
}
```

```javascript
  location /_nuxt/hmr/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass http://tres_rios_app_upstream/;
  }
```

**Comment by ayalon** [comment]
It is a regression introduced with nuxt cli 3.12.2

It took me hours to understand the issue. Nuxt is using Vite for HMR. Usually, Nuxt run on a Port (3000) and Vite has its own port. On this port, Vite exposes a Websocket that is used to updated the website client side.

[Nuxt changed that behaviour with a trick ](https://github.com/nuxt/cli/pull/184)and is sharing the same port for Nuxt and Vite. This is done with some hook in nuxi when starting Nuxt.

Last week this behavior was changed and now it breaks if you run your frontend with HTTPS behind a reverse proxy.
Setting custom options in vite has no impact, because the settings are overridden with from Nuxt (except you set en environment variable called `NUXI_DISABLE_VITE_HMR=TRUE`

But if you do so, Vite and Nuxt will no longer share on the same port and then our reverse proxy setup no longer works. So this is not a way to go.
Example that does NOT work:
```
vite: {
  server: {
    hmr: {
      protocol: 'wss',
    },
    }
  }
}
```
Add this hook to you nuxt.config.ts until this is fixed upstream
```
  hooks: {
    'vite:extend'({ config }) {
      if (config.server && config.server.hmr) {
        // @ts-ignore
        config.server.hmr.protocol = 'wss'
      }
    },
  },
```

**Comment by cmd430** [comment]
I'm fairly sure it was something about this change that has caused the regression https://github.com/nuxt/cli/commit/1bbd196a931c855e6b1cc526f9f0809d0defaa22 

in [src/utils/dev.ts](https://github.com/nuxt/cli/pull/420/commits/421e827c7b88172961837ba03bd296c3f090be46#diff-aa1f0f013b0d7107d2294c00206c16c84fbb24bbaf76accab551e331dbeb97bd) changing `config.server.hmr = {...}` ([Lines 193-199](https://github.com/nuxt/cli/pull/420/commits/421e827c7b88172961837ba03bd296c3f090be46#diff-aa1f0f013b0d7107d2294c00206c16c84fbb24bbaf76accab551e331dbeb97bdR193-R199)) to the following 
```diff
config.server.hmr = {
+  protocol: undefined,
  ...(config.server.hmr as Exclude<typeof config.server.hmr, boolean>),
-  protocol: undefined,
  port: undefined,
  host: undefined,
  server: this.listener.server,
}
```
fixes it for me and allows setting the protocol with the normal config option again
```js
vite: { 
  server: { 
    hmr: { protocol: 'wss' } 
  } 
}`
```

This can be done with the current release by editing `node_modules\nuxi\dist\chunks\dev2.mjs`  at lines 6853-6859
```diff
config.server.hmr = {
+  protocol: void 0,
  ...config.server.hmr,
-   protocol: void 0,
  port: void 0,
  host: void 0,
  server: this.listener.server
};

**Comment by danielroe** [comment]
Would you provide a reproduction please? 🙏

**Comment by Ingramz** [comment]
Probably quickest way to reproduce is using [Caddy](https://caddyserver.com/).

Add `127.0.0.1 nuxt.local` to hosts file or change the domain to any local domain below:
`caddy reverse-proxy --internal-certs --from nuxt.local --to localhost:3000`

Start nuxt dev server (no `nuxt.config` changes needed, so a new empty project will suffice), then visit `https://nuxt.local` and notice that it will complain about insecure protocol used in the devtools console. Also changes in any of the `.vue` files will not trigger HMR in browser.

This works fine when nuxi is downgraded back to `3.11.1` or earlier via `package.json`:
```json
  "overrides": {
    "nuxi": "3.11.1"
  }
```

**Comment by bennyzen** [comment]
When using pnpm as package manager, you'll probably need to add this to your `package.json`, using this notation:
```json
"pnpm": {
    "overrides": {
      "nuxt>nuxi": "3.11.1"
    }
  }
```

**Comment by danielroe** [comment]
Thank you for the reproduction! This should be resolved in the next `nuxi` release 🙏

**Comment by db-lyon** [comment]
I've been banging my head against the wall on this for 2 days. The workaround seems to move the needle on `host` and `protocol` but i cannot for the life of me get `port` to map.

I've resorted to disabling HMR for now.

**Comment by chrisspiegl** [comment]
Dear @danielroe, I see that you mention this should be fixed in the next release.

- How does one know when the next release is?
- Would it make sense to keep this issue open and close it once it is actually fixed and released?
- I just tried to update nuxt/nuxi, and it appears not released at this time.

I, personally, have seen these "closing it's going to be release in the next release" on a few packages (Firebase for example) and then no one knows when that release will actually happen.

Maybe I am missing something or don't comprehend how we would know, but when tracking an issue like this, I find it difficult to stay up to date when it's closed without actually being fixed & released. Which is also signified by others opening new issues like https://github.com/nuxt/nuxt/issues/28082 which is probably a duplicate of this one here.

**Comment by slavanossar** [comment]
@chrisspiegl This doesn't fully answer your question, but a helpful tip is that you can watch repositories and receive notifications specifically when new releases come out.

It's still up to you to check the notification and see if the fix you are interested is included in the release, but it's makes it a lot easier to keep track of. I also just find it quite useful to enable for all larger packages I use regularly to see what features are being added.

1. Click the `Watch` button in the repository, select `Custom`
<img width="492" alt="image" src="https://github.com/user-attachments/assets/40d5f3ac-57e2-4c92-a7a2-8ae141f8d730">

2. Select `Releases` (and any other notifications you want to receive), 
<img width="494" alt="image" src="https://github.com/user-attachments/assets/9a43751c-839b-450b-aa36-e0a67de13f8f">

**Comment by chrisspiegl** [comment]
I know about getting notifications upon GitHub release tags, but I wonder if there is a better way, like:

- closing issues when they are actually released instead of fixed
- or maybe when it's fixed and closed, stating that there will be an update comment upon release.

I know this is something that at least pull requests do show with the "This PR’s merge commit doesn’t appear in any tags". Perhaps something similar can be achieved with issues upon release?

I realize, this is "off-topic", so I'll leave it at that. But I hope this can be improved for projects like this.

**Comment by danielroe** [comment]
I think it’s a good idea and have been thinking about a bot to comment when a release incorporating a fix is made.

**Comment by Ingramz** [comment]
Reproduction over at https://github.com/nuxt/nuxt/issues/27558#issuecomment-2188504331 still fails with nuxt 3.13.1 & nuxi 3.13.1

It looks like the value evaluated here becomes the default, which did not happen before the changes in https://github.com/nuxt/cli/pull/420

https://github.com/nuxt/nuxt/blob/6c98cdc645060b0eea311dcc42f8834a10117011/packages/vite/src/client.ts#L178-L182

Still not quite sure of the order of operations here, when which part of the configuration gets applied, but I think one way to work around this would be to not assume that `devServer.https` being falsy automatically means that we are using an insecure protocol in the browser. Leaving the false branch `undefined` here should let vite automatically detect based on the url protocol in browser whether to use `ws` or `wss` as the previous commenter tried to explain:

`const socketProtocol = __HMR_PROTOCOL__ || (importMetaUrl.protocol === 'https:' ? 'wss' : 'ws')`

@danielroe any thoughts?
