### ISSUE TITLE
Nuxt restarts when data in sqlite .db file is updated in directory root

### ISSUE THREAD

**Issue by matt-clegg** [nuxt/nuxt#29813]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.15.0
- Nuxt Version:     3.14.0
- CLI Version:      3.15.0
- Nitro Version:    -
- Package Manager:  pnpm@9.4.0
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

To recreate this issue I used Drizzle ORM and added a button to app.vue in order to save some data into a .db file.

1. Create a new empty Nuxt project with `pnpx nuxi init <app>`.
2. Inside the nuxt.config.ts file, set the compatibility version to 4 with `future: { compatibilityVersion: 4 },` and compatibility date to: `compatibilityDate: "2024-07-30",`, move the app.vue file into the /app directory.
3. Install Drizzle ORM dependency and Drizzle Kit as a dev dependency.
4. Configure Drizzle to use sqlite and store the database in the root directory.
5. Create a simple Drizzle table schema and a server API endpoint to create data in the table.
6. Generate a migration and update the database with the migration with: `drizzle-kit generate` then `drizzle-kit migrate`.
8. Create a button in the app.vue file to call the server API endpoint.
9. Run project, click the button to add data to the database, Nuxt will "restart".

I used the following guide to setup Drizzle: [https://orm.drizzle.team/docs/get-started/sqlite-new](https://orm.drizzle.team/docs/get-started/sqlite-new)

This is what some key files contain.

.env
```
DB_FILE_NAME=file:local.db
```

drizzle.config.ts
```ts
import {defineConfig} from "drizzle-kit";

export default defineConfig({
  out: './server/database/migrations',
  schema: './server/database/schema.ts',
  dialect: 'sqlite',
  dbCredentials: {
    url: process.env.DB_FILE_NAME!,
  },
});
```

/server/database/schema.ts
```ts
import { integer, text, sqliteTable } from "drizzle-orm/sqlite-core";

export const user = sqliteTable("users", {
  id: integer("id").primaryKey({autoIncrement: true}),
  name: text("name").notNull()
})
```

/server/database/drizzle.ts
```ts
import {drizzle} from "drizzle-orm/libsql";

export function useDrizzle() {
  return drizzle( process.env.DB_FILE_NAME! );
}
```

/server/api/users/index.post.ts
```ts
import { useDrizzle } from "../../database/drizzle";
import { user } from "../../database/schema";

export default eventHandler(async (event) => {
  const body = await readBody(event);
  await useDrizzle().insert(user).values(body);
})
```

/app/app.vue
```vue
<script setup lang="ts">
async function createUser() {
  await $fetch( "/api/users", {
    method: "POST",
    body: {
      name: "Person Name",
    },
  } );
}
</script>

<template>
  <div>
    <button @click="createUser">Create</button>
  </div>
</template>
```

### Describe the bug

When data in a sqlite database, located in the root directory, is modified, the Nuxt process will restart. For some reason Nuxt thinks the nuxt.config.ts file has been updated when a change is made to the database.

```
√ Nuxt Nitro server built in 1597 ms                                                                                                                                      nitro 08:24:56
i nuxt.config.ts updated. Restarting Nuxt...                                                                                                                                    08:25:15
  ➜ DevTools: press Shift + Alt + D in the browser (v1.6.0)                                                                                                                     08:25:16

i Running with compatibility version 4                                                                                                                                          08:25:16
√ Vite client built in 28ms                                                                                                                                                     08:25:16
√ Vite server built in 268ms                                                                                                                                                    08:25:17
 ELIFECYCLE  Command failed with exit code 3221225477.

```

This doesn't happen if the .db file is moved into it's own directory, eg `/data/local.db`.

**Comment by matt-clegg** [comment]
I updated to v3.14.159 and the same thing still happens when the .db file is updated.

**Comment by matt-clegg** [comment]
Unfortunately I wasn't able to create a repro on stackblitz or codesandbox. Instead, here's the reproduction in a git repo.

To get the reproduction to work, you'll need to run the `db:migrate` script before running the dev server.

If there are any issues with it do let me know.

https://github.com/matt-clegg/nuxt-restart-issue-repro

**Comment by Mobyrr** [comment]
I have the same (or similar) bug with "ℹ Directory utils/ removed" and only when it's a POST request (PATCH or DELETE work fine)

**Comment by ibtorsleff** [comment]
With Nuxt  v3.14.159 I can confirm the same bug on DB updates when the .db file is in the nuxt root folder. (works fine when the local Db is in another folder.

**from package.json**:
"dependencies": {
    "@libsql/client": "^0.14.0",
    "drizzle-orm": "^0.36.3",
    "nuxt": "^3.14.159",
    "vue": "latest",
    "vue-router": "latest"
  },
  "devDependencies": {
    "drizzle-kit": "^0.28.1"
  }
**nuxt.config.ts:**
export default defineNuxtConfig({
  //compatibilityDate: '2024-04-03',
  devtools: { enabled: true },

  future: {
    compatibilityVersion: 4,
  },

  compatibilityDate: '2024-11-17',
})

**.env:**
DB_FILE_NAME=file:./server/db/local.db

**Comment by AntonyZ89** [comment]
Nuxt v3.14.1592

Same here... `.sqlite` files in the root directory refresh the application.

`.nuxtignore` and `vite.server.watch.ignored` don't work; the only real solution is to move the .sqlite file to another folder.

Nuxt logs indicate that `nuxt.config.ts` is being changed, not that `db.sqlite` has changed. Clearer logs would help a lot in identifying the root of the problem.

**Comment by danielroe** [comment]
@matt-clegg looking at that reproduction (with `compatibilityVersion: 4`), I do not see any issue

https://github.com/user-attachments/assets/dd80aa1a-5f30-457c-991c-460a2ed3edbb

this is also the case when I disable `compatibilityVersion` and move `app.vue` back to the root directory.

Does it still reproduce for you? (It could be another dependency that's been updated in the meanwhile.)

**Comment by beyer96** [comment]
I confirm this issue still persists and it is not windows-only issue. On windows, I get `nuxt.config.ts updated ...` issue, as described by @matt-clegg. However when I ran same project on Ubuntu, I got `components/ updated ...` - which in the end leads to same issue, but was quite surprise that on different OS it points to 'update' of completely different files.

Both of these issues happens after I trigger PUT request. Link to my repo: https://github.com/beyer96/nuxt-todo 

I also confirm that the solution from @ibtorsleff resolves this problem.

**Comment by ibtorsleff** [comment]
@danielroe Thanks for looking into this 
In my case the project is located here : C:\Dev\Repos\NuxtDrizzleTest
It was as fresh as possible the only purpose of the project was to try out drizzle in the minimalistic form
I use NPM on windows 11, no WSL involved 
...ib

**Comment by danielroe** [comment]
@beyer96 FWIW the error you're seeing there will be fixed in v3.15, but that's produced by the restart, and doesn't _cause_ it.

**Comment by ThimoDEV** [comment]
I just encountered the issue too.

Environment: windows 11
Nuxt: 3.15.1

When db file is in root it causes a restart. When it is inside another file it works

**Comment by ThimoDEV** [comment]
https://github.com/ThimoDEV/nuxt-sql-root-bug

Here is a reproduction I could make. I hope you have it too @danielroe 

Please let me know if you need more info :)

**Comment by diameter9836** [comment]
I'm having the same problem now.
My project uses the following configurations:
- nuxt: 3.17.2
- trpc-nuxt: 1.2.0
- node: 20.19.4
- drizzle-orm: 0.44.2
- sqlite.db is located in the root directory

There are some route files under /server/trpc/routers/ in my project.

<img width="630" height="493" alt="Image" src="https://github.com/user-attachments/assets/15f32be7-4bf6-4886-953e-82dda27c4238" />

Everything works fine when I start the project. However, whenever I modify any file in the routers directory (even just adding logs), a 503 Service Unavailable error occurs.

This issue mentions that problems may arise when the sqlite.db file changes, but in my case, queries simply fail to work at all.

Similarly, when I move the .db file to a non-root directory, the problem is resolved and everything works normally.

I can organize the code to reproduce the issue if needed.

**Comment by diameter9836** [comment]
I don't know why, the same error occurred again. when I modified the server/trpc directory, the project will prompt Dev server is unavailable

**Comment by wodepig** [comment]
I also encountered the problem of consent. I used trpc-nuxt and sqlite, which were not solved after many tests. finally, I replaced mysql. everything is normal at present.
demo  repo: https://github.com/wodepig/nuxt-trpc-err
[nuxt3: trpc-nuxt和sqlite导致的503错误](https://www.xxdl.xyz/archives/nuxt-trpc-503-error-sqlite)

**Comment by husayt** [comment]
I have started  seeing this error on latest nuxt after I added @nuxt/MDC module.

Environment : Win 11
Nuxt 4.3.1
nuxt ui: 4.5.1
node: 24.13.0
