### ISSUE TITLE
watcher scans all files in root directory

### ISSUE THREAD

**Issue by AlansCodeLog** [nuxt/nuxt#30023]
### Environment

- Operating System: Linux
- Node Version:     v22.10.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.10.4
- Package Manager:  pnpm@9.12.2
- Builder:          -
- User Config:      default
- Runtime Modules:  -
- Build Modules:    -

### Reproduction

To truly recreate, you would have to install devenv and create a basic environment. Then run something like `htop` which gives the full process command, press F4 to filter and type nuxi you should see that when you start nuxt a bunch of node nuxi processes are created, but then when you quit some remain in D state and cannot be killed.

**Alternatively**, I managed to half recreate this by copying and pasting a newly initialized .devenv folder from my project into a freshly created nuxt project.

After a bit of digging, I realized if I just created a symlink in the .devenv folder I would get an error. Nuxt still runs in this case because it's not a true symlink to the nix store, but there's definitely something watching a folder it shouldn't.

```
 ERROR  [unhandledRejection] ELOOP: too many symbolic links encountered, stat '/home/alan/code/nuxt-zombie-watcher-issue/.devenv/test'
```
https://stackblitz.com/edit/github-6rzbve?file=README.md

### Describe the bug

I'm not 100% sure what's going on, but I *think* something is trying to watch directories it shouldn't.

I'm on nixos and use devenv to create local dev environments and it creates a folder called `.devenv`. This contains all the state for the databases, etc, and symbolic links to executables in the nix store. I have this folder added to the `.nuxtignore`.

But I started noticing that I was running out of RAM when I shouldn't be after a while developing. I also started to get errors when stopping and re-running nuxt that I reached the system file limit for watchers (sometimes the warning was about files inside the `.devenv` folder, though I didn't notice at first). Odd.

I look at htop and see there are a bunch of unkillable (in D state) zombie nuxi processes. After much copying, pasting, and restarting, I narrow the problem down to the existence of the .devenv folder and the symlinks inside of it (see reproduction notes). I lifted it up the dev environment config/folders up a directory (not ideal) and the issue was gone. 

### Logs

```shell-script

```

**Comment by manniL** [comment]
Does this also happen with the new v4 compatibility mode ([check here on how to enable it](https://nuxt.com/docs/getting-started/upgrade#testing-nuxt-4))?

**Comment by AlansCodeLog** [comment]
Yes.

Also, I just realized I hadn't saved my changes to stackblitz (just updated it and set to use v4) and it's deleting the hidden folder + symlink. Not sure why. 

So to actually reproduce do:

```
mkdir test
mkdir .shouldbeignored
ln -s test .shouldbeignored/test
rm -rf test 
npm run dev
```

**Comment by AlansCodeLog** [comment]
Weird that I get too many watcher errors then (when the folder is actually symlinked to something big)... It seems like maybe chokidar or vite? are not releasing something as the zombie process issue happens no matter how long the server has been running. I would assume the initial scan would finish at some point and there wouldn't be a problem.

Can the allowed dirs be overridden somehow? Given what you said, I tried splicing the root dir out of `config.server.fs.allows` (that is the property you mean yes?) in a `vite:extendsConfig` hook, but this seems to run after the error. Also tried setting `vite.server.fs.deny`. No luck.

**Comment by danielroe** [comment]
@AlansCodeLog If you aren't using the v4 compatibility mode, you can set `experimental.watcher` to `chokidar` which should reduce watcher count.

**Comment by thorge** [comment]
I'm encountering a similar issue. I have a large number of files and folders (>30k) in my public directory, and I run out of file watchers. Increasing the number of watchers isn't an option because my RAM isn't sufficient to handle the heap.

Error message:
```
Cannot start nuxt: ENOSPC: System limit for number of file watchers reached, watch ...
```

I've tried several solutions, including setting `experimental.watcher`, enabling v4 compatibility mode, and adjusting various Nuxt config options like:

```js
watchers: {
  chokidar: {
    ignoreInitial: true,
    ignored: ["public/data/"]
  }
},
```
and
```js
ignore: ["public/data/"]
```

But the issue persists.

**Comment by danielroe** [comment]
maybe linked: https://github.com/nuxt/nuxt/issues/30137

**Comment by hendrikheil** [comment]
We encountered the same using nix and direnv. direnv creates a top-level `.direnv` folder that has a symlink to the nix store used in our projects. That seems to be scanned when using `chokidar=^4.0`. Switching to `parcel` as the watcher was a band-aid fix for us.

**Comment by AlansCodeLog** [comment]
@hendrikheil Did you also have the zombie process issue? I tried switching to parcel and had the same issue, but maybe I was doing something wrong (I tried so many things 😅). I'll give it another try.

**Comment by hendrikheil** [comment]
Yep, I also saw the zombie process. But with parcel there is no zombie anymore, I just tried it.

**Comment by oxcabe** [comment]
Same as @hendrikheil - using Nix and direnv in a fresh new Nuxt project. Setting the watcher to `parcel` does the trick as a workaround:

```ts
export default defineNuxtConfig({
  compatibilityDate: '2024-11-01',
  devtools: { enabled: true },
  experimental: { watcher: "parcel" }
})
```

**Comment by AlansCodeLog** [comment]
Can also now confirm the parcel watcher works.

**Comment by danielroe** [comment]
the zombie process issue should be fixed with latest `nuxi` via https://github.com/nuxt/cli/pull/602

@AlansCodeLog - in your can also try `chokidar-granular` (which was originally created as a watcher strategy to work around the performance issues of watching a directory which also contained `node_modules` and `.git`)

**Comment by productdevbook** [comment]
```
nuxt.hook('builder:watch', async (event, path) => {
```

Interestingly, the file in the server files is no longer being listened to. I am using future: { compatibilityVersion: 4 }. I’m not sure if this is related to the issue.

**Comment by L33Z22L11** [comment]
I’m experiencing a similar issue on Windows with Nuxt 3.14.0 and above, using the `{compatibilityVersion: 4}` configuration. I’ve noticed persistent high CPU usage and memory consumption gradually increasing up to 8GB within half an hour of development. Upon debugging with Node, I can see numerous `fsWatch` entries in the performance graph, indicating that file watchers are being triggered unnecessarily. This seems to be related to excessive watching of files or directories that shouldn't be under watch. I had to downgrade to Nuxt 3.13.2 to avoid this. Is there any insight into a possible cause or a workaround for this?

**Comment by hendrikheil** [comment]
@danielroe I think the issue isn't resolved yet, so maybe this should be re-opened?

I created a reproduction of our exact environment (were using nix and direnv for reproducable dev environments) here: https://github.com/hendrikheil/nuxt-watcher-too-many-open-files

Changing the watcher to `parcel` also doesn't seem to fix it for us anymore.

**Comment by hendrikheil** [comment]
For those of you out there using `direnv`, adding this snippet to your `.envrc` file (either per-project or global), will move the `.direnv` folder out of the project root.

I don't think thats a particularly ideal solution, but should be a band-aid solution until a proper solution is around.

You can of course change the directory path to whatever you'd prefer.

```
pwd_hash=$(basename $PWD)-$(echo -n $PWD | shasum | cut -d ' ' -f 1)
direnv_layout_dir="$HOME/.cache/direnv/layouts/$pwd_hash"
```

**Comment by mcfarljw** [comment]
I'm stuck on `Nuxt 3.13.2` too because of the "too many open open files issue" issues (previously was commenting over here https://github.com/nuxt/nuxt/issues/12376) and have tried quite a few things unsuccessfully. The main problem is that I have have an `ionic/` directory which contains 10 different Ionic Capacitor apps that each have platforms for Android/iOS (so a large number of files).

I've tried numerous ways of ignoring things are shown below:

```ts
export default defineNuxtConfig({
    compatibilityDate: '2024-11-01',
    future: {
        compatibilityVersion: 4,
    },
    ignore: ['ionic/**/*'],
    nitro: {
        watchOptions: {
            ignored: ['ionic/**/*'],
        },
    },
    watchers: {
        chokidar: {
            ignored: ['ionic/**/*'],
        },
    },
})

```

I've even tried `experimental: { watcher: "parcel" }` but the same issue persists. I've noticed that `chokidar` still seems to be stack trace even with parcel enabled though that might be coming from `nitro` if it doesn't honor that config setting. I'd really like to upgrade to a later version of Nuxt to take advantage of the improved file structure.

My current workaround is to use `nodemon` to watch for file changes and then run `npm run build` so that I can preview the changes 😬

**Comment by danielroe** [comment]
There are a lot of things that spawn watchers. You can control what _nuxt_ uses, but Vite, unstorage, nitro and others have their own watchers, most of which use chokidar.

The upgrade to chokidar v4 across the ecosystem has caused this as it doesn't support glob any more, so any watchers which aren't migrated across might be watching too much. In addition, I think having v4 and v3 in the same project may cause at least 2x as many files being opened in the fs, as (probably) it can't be deduplicated across major versions. (But this is just a guess and I might be wrong about it.)

**Comment by mcfarljw** [comment]
Thanks for additional insights @danielroe and for confirming that while Nuxt might be handling watchers correctly it could be an upstream issue. Now that you mention it, I also did see `unstorage` in a few of the stack traces as well. Right now it kind of feels like if you're using anything greater than `Nuxt 3.13.2` and have a directory which contains more than X number of files, even if it's not being used by Nuxt, you won't be able to run the dev command.

I'd love to help out but I'm unsure of the best way to do so. I'm currently just running the debugger and following stack traces to see where things are being watched from that I don't want watched. I'd be willing to add you or anyone else on the team as a contributor to one of my projects with this issue if having a real world reproduction would help (unfortunately I can't make the repo public).

**Comment by phbe** [comment]
Just a short heads-up, maybe helpful for everyone using `devenv.sh`: Since updating `devenv.sh` to version `1.5.0`, I’ve been unable to start any Nuxt project with `npm run dev` (on a Mac m4, fails with `EMFILE: too many open files, watch` ). Even explicitly overriding `chokidar` to version `^3.6.0` doesn’t help (this makes it fail with `ELOOP: too many symbolic links encountered...`)

The issue seems to be related to a new feature in `devenv` that allows setting the macOS SDK in the shell (https://github.com/cachix/devenv/pull/1686).

What worked for me was adding `apple.sdk = null;` in the `devenv.nix` file (https://devenv.sh/common-patterns/#link-against-macos-system-frameworks).

**Comment by danielroe** [comment]
this should be resolved in the new folder structure in nuxt v4 via https://github.com/nuxt/nuxt/pull/27029.

if you have that enabled and are still getting watcher-related issues, please let me know (or open a new issue) with a reproduction 🙏

**Comment by NDKhanh96** [comment]
So this bug cannot be fixed in nuxt 3?

**Comment by azuken** [comment]
Still have the issue at build time with Nuxt 4.1.2 (and randomly, when I relaunch my Gitlab CI job, it usually works)

```sh
Running with gitlab-runner 17.3.3 (26a9eefc)
  on Runner _g8cfjFhd, system ID: r_OmK1KWgFQR1z
Preparing the "docker" executor
00:02
Using Docker executor with image node:24-alpine ...
Pulling docker image node:24-alpine ...
Using docker image sha256:e4a821e4027215700f8fd1dfd8097b2850da80a229c24d4f7e4fb0015f04bdd8 for node:24-alpine with digest node@sha256:f36fed0b2129a8492535e2853c64fbdbd2d29dc1219ee3217023ca48aebd3787 ...
Preparing environment
00:01
Running on runner-g8cfjfhd-project-215-concurrent-1 via xxxx.net...
Getting source from Git repository
00:04
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/xxx/frontend/.git/
Checking out 2ed4a080 as detached HEAD (ref is refs/merge-requests/440/head)...
Removing .nuxt/
Removing .output/
Removing .yarn/cache/
Removing .yarn/install-state.gz
Removing node_modules/
Skipping Git submodules setup
Downloading artifacts
00:15
Downloading artifacts for install (148009)...
Downloading artifacts from coordinator... ok        host=xxx.net id=148009 responseStatus=200 OK token=glcbt-64
Executing "step_script" stage of the job script
00:41
Using docker image sha256:e4a821e4027215700f8fd1dfd8097b2850da80a229c24d4f7e4fb0015f04bdd8 for node:24-alpine with digest node@sha256:f36fed0b2129a8492535e2853c64fbdbd2d29dc1219ee3217023ca48aebd3787 ...
$ yarn build
[log] [nuxi] Nuxt 4.1.2 with Nitro 2.12.6
[info] [nuxt:tailwindcss] Using default Tailwind CSS file
[info] [nuxi] Building for Nitro preset: `node-server`
[info] Building client...
[info] vite v7.1.5 building for production...
[info] transforming...
[info] ✓ 1366 modules transformed.
[info] rendering chunks...
[info] computing gzip size...
[info] ../.nuxt/dist/client/manifest.json                              18.61 kB │ gzip:   2.28 kB
[info] ../.nuxt/dist/client/_nuxt/PPSupplyMono-Variable.DsInnWUg.ttf   48.70 kB
[info] ../.nuxt/dist/client/_nuxt/PPSupplySans-Variable.Cbc3b6Ny.ttf   99.08 kB
[info] ../.nuxt/dist/client/_nuxt/Inter-Variable.Cl4AQHp9.ttf         804.61 kB
[info] ../.nuxt/dist/client/_nuxt/entry.BlgYmPsC.css                   98.62 kB │ gzip:  15.71 kB
[info] ../.nuxt/dist/client/_nuxt/PalxAwQ_.js                           0.06 kB │ gzip:   0.08 kB
[info] ../.nuxt/dist/client/_nuxt/BVQCr-HH.js                           0.07 kB │ gzip:   0.08 kB
[info] ../.nuxt/dist/client/_nuxt/A7XietjN.js                           0.09 kB │ gzip:   0.11 kB
[info] ../.nuxt/dist/client/_nuxt/eGeoT8Mx.js                           0.19 kB │ gzip:   0.17 kB
[info] ../.nuxt/dist/client/_nuxt/a6N01NEo.js                           0.29 kB │ gzip:   0.24 kB
[info] ../.nuxt/dist/client/_nuxt/CO4eJk4_.js                           0.44 kB │ gzip:   0.24 kB
[info] ../.nuxt/dist/client/_nuxt/wqi1_Ivh.js                           0.45 kB │ gzip:   0.32 kB
[info] ../.nuxt/dist/client/_nuxt/-QM2LZfv.js                           0.50 kB │ gzip:   0.27 kB
[info] ../.nuxt/dist/client/_nuxt/BE4T2eyI.js                           0.50 kB │ gzip:   0.33 kB
[info] ../.nuxt/dist/client/_nuxt/CfCIW3_P.js                           0.50 kB │ gzip:   0.34 kB
[info] ../.nuxt/dist/client/_nuxt/Bb7irpQQ.js                           0.53 kB │ gzip:   0.34 kB
[info] ../.nuxt/dist/client/_nuxt/DLQj89rw.js                           0.65 kB │ gzip:   0.44 kB
[info] ../.nuxt/dist/client/_nuxt/Pa7JVaRF.js                           0.78 kB │ gzip:   0.52 kB
[info] ../.nuxt/dist/client/_nuxt/A8UjhRbc.js                           0.80 kB │ gzip:   0.32 kB
[info] ../.nuxt/dist/client/_nuxt/BqM_btjm.js                           0.86 kB │ gzip:   0.52 kB
[info] ../.nuxt/dist/client/_nuxt/BJJZNqVX.js                           1.00 kB │ gzip:   0.52 kB
[info] ../.nuxt/dist/client/_nuxt/D3JRB0r0.js                           1.08 kB │ gzip:   0.50 kB
[info] ../.nuxt/dist/client/_nuxt/Cue3V_FK.js                           1.08 kB │ gzip:   0.53 kB
[info] ../.nuxt/dist/client/_nuxt/CnnyMgx0.js                           1.23 kB │ gzip:   0.56 kB
[info] ../.nuxt/dist/client/_nuxt/Dkz3ruiP.js                           2.02 kB │ gzip:   1.12 kB
[info] ../.nuxt/dist/client/_nuxt/CoUxbnMF.js                           2.81 kB │ gzip:   1.47 kB
[info] ../.nuxt/dist/client/_nuxt/3NPUAri6.js                           2.89 kB │ gzip:   1.40 kB
[info] ../.nuxt/dist/client/_nuxt/_RM4p1l0.js                           3.02 kB │ gzip:   1.32 kB
[info] ../.nuxt/dist/client/_nuxt/BHedYLJy.js                           3.21 kB │ gzip:   1.71 kB
[info] ../.nuxt/dist/client/_nuxt/DJI6WCqE.js                           3.82 kB │ gzip:   1.65 kB
[info] ../.nuxt/dist/client/_nuxt/BUcMvmKv.js                           3.97 kB │ gzip:   1.79 kB
[info] ../.nuxt/dist/client/_nuxt/DwMOEBXN.js                           4.25 kB │ gzip:   1.75 kB
[info] ../.nuxt/dist/client/_nuxt/CwtvwXb3.js                           5.76 kB │ gzip:   2.37 kB
[info] ../.nuxt/dist/client/_nuxt/Cicns1-J.js                           6.42 kB │ gzip:   2.35 kB
[info] ../.nuxt/dist/client/_nuxt/B3rtC_LU.js                           6.84 kB │ gzip:   2.22 kB
[info] ../.nuxt/dist/client/_nuxt/g1k1nztJ.js                           6.98 kB │ gzip:   2.45 kB
[info] ../.nuxt/dist/client/_nuxt/CdfDu96z.js                           7.11 kB │ gzip:   3.58 kB
[info] ../.nuxt/dist/client/_nuxt/__-fOtTS.js                           7.51 kB │ gzip:   2.69 kB
[info] ../.nuxt/dist/client/_nuxt/BTMy3mIM.js                           7.64 kB │ gzip:   3.02 kB
[info] ../.nuxt/dist/client/_nuxt/CmWBdUSh.js                           7.75 kB │ gzip:   2.69 kB
[info] ../.nuxt/dist/client/_nuxt/Dlk9BmYR.js                           7.82 kB │ gzip:   2.78 kB
[info] ../.nuxt/dist/client/_nuxt/Z34NSFI4.js                           8.15 kB │ gzip:   3.28 kB
[info] ../.nuxt/dist/client/_nuxt/BN8ADEIl.js                           8.70 kB │ gzip:   3.16 kB
[info] ../.nuxt/dist/client/_nuxt/BJ0hOTxw.js                           8.73 kB │ gzip:   3.09 kB
[info] ../.nuxt/dist/client/_nuxt/kGzgt4mY.js                           8.96 kB │ gzip:   3.33 kB
[info] ../.nuxt/dist/client/_nuxt/Ct3TI4n5.js                          10.52 kB │ gzip:   4.18 kB
[info] ../.nuxt/dist/client/_nuxt/XT_vCuc9.js                          10.58 kB │ gzip:   3.47 kB
[info] ../.nuxt/dist/client/_nuxt/CeEojQI-.js                          11.98 kB │ gzip:   4.79 kB
[info] ../.nuxt/dist/client/_nuxt/drUFHnQ5.js                          12.48 kB │ gzip:   4.47 kB
[info] ../.nuxt/dist/client/_nuxt/BJgBdrJx.js                          14.27 kB │ gzip:   5.01 kB
[info] ../.nuxt/dist/client/_nuxt/ex8Kq77_.js                          18.79 kB │ gzip:   6.43 kB
[info] ../.nuxt/dist/client/_nuxt/COZlZ-tD.js                          22.74 kB │ gzip:   6.81 kB
[info] ../.nuxt/dist/client/_nuxt/DUxSDw3f.js                          24.97 kB │ gzip:   5.99 kB
[info] ../.nuxt/dist/client/_nuxt/B2vDC9cd.js                          26.53 kB │ gzip:   6.51 kB
[info] ../.nuxt/dist/client/_nuxt/Y7rsSwr0.js                          27.08 kB │ gzip:   6.79 kB
[info] ../.nuxt/dist/client/_nuxt/CwhhWZUF.js                          27.51 kB │ gzip:  11.02 kB
[info] ../.nuxt/dist/client/_nuxt/DiK804Nw.js                          27.61 kB │ gzip:   6.75 kB
[info] ../.nuxt/dist/client/_nuxt/Djjc2Slk.js                          29.90 kB │ gzip:   7.40 kB
[info] ../.nuxt/dist/client/_nuxt/DLcqtb0T.js                          39.29 kB │ gzip:  11.25 kB
[info] ../.nuxt/dist/client/_nuxt/BFfIi9MP.js                          41.87 kB │ gzip:  17.07 kB
[info] ../.nuxt/dist/client/_nuxt/BGBDbnFo.js                         116.79 kB │ gzip:  32.83 kB
[info] ../.nuxt/dist/client/_nuxt/C4H0YLeQ.js                         184.24 kB │ gzip:  58.73 kB
[info] ../.nuxt/dist/client/_nuxt/CmbYyOUX.js                         348.84 kB │ gzip:  87.78 kB
[info] ../.nuxt/dist/client/_nuxt/DKLV0bhc.js                         937.47 kB │ gzip: 309.98 kB
[warn] 
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
[info] ✓ built in 12.78s
[success] Client built in 12813ms
[info] Building server...
[info] vite v7.1.5 building SSR bundle for production...
[info] transforming...
[info] ✓ 558 modules transformed.
[info] rendering chunks...
[info] ✓ built in 5.36s
[success] Server built in 5380ms
[success] [nitro] Generated public .output/public
PWA v1.1.0
mode      generateSW
precache  89 entries (4230.85 KiB)
files generated
  ../.output/public/sw.js
  ../.output/public/workbox-75c93c3c.js
[info] [nitro] Building Nuxt Nitro server (preset: `node-server`, compatibility date: `2024-07-10`)
[success] [nitro] Nuxt Nitro server built
[error] ELOOP: too many symbolic links encountered, scandir '/builds/xxx/frontend/.output/server/node_modules/.nitro/vue-router@4.6.3/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/dist'
   
[error] ELOOP: too many symbolic links encountered, scandir '/builds/xxx/frontend/.output/server/node_modules/.nitro/vue-router@4.6.3/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/node_modules/@vue/server-renderer/node_modules/vue/dist'
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by vindard** [comment]
> this should be resolved in the new folder structure in nuxt v4 via [#27029](https://github.com/nuxt/nuxt/pull/27029).
> 
> if you have that enabled and are still getting watcher-related issues, please let me know (or open a new issue) with a reproduction 🙏

@danielroe https://github.com/nuxt/nuxt/issues/30756#issuecomment-3733231624
