### ISSUE TITLE
after update from 4.2.1 to 4.2.2 not work autocomplete in webstorm

### ISSUE THREAD

**Issue by FlexIDK** [nuxt/nuxt#33877]
### Environment

Node.js version       v24.12.0
nuxt/cli version      3.31.2
Package manager       npm 11.7.0
Nuxt version          4.2.2
Nitro version         2.12.9
Builder               vite 7.2.7

### Reproduction

update from 4.2.1 to 4.2.2 and rebuild .nuxt folder or create new vue component

### Describe the bug

After running npm run dev, the file .nuxt/types/components.d.ts contains an incorrect path to components.
- In version 4.2.1, the path is generated as:
`'ComponentName': typeof import("../../app/components/component-name.vue")['default']`
 
- In version 4.2.2, the path is generated as:
`'ComponentName': typeof import("../../app/components/component-name.vue").default`

After this change, autocomplete and "Go to Declaration" in WebStorm (JetBrains) stop working.
If manually replace .default with ['default'], autocomplete works again.

### Logs

```shell-script

```

**Comment by FlexIDK** [comment]
[v4.2.2](https://codesandbox.io/p/live/e8938f8f-06da-4924-9cb7-338a65f7f62a)
look file: .nuxt/types/components.d.ts
`interface _GlobalComponents {
  'Test': typeof import("../../app/components/test.vue").default`

[v4.2.1](https://codesandbox.io/p/live/2f081157-0c69-4fab-af66-844669bfd3bf)
look file: .nuxt/types/components.d.ts
`interface _GlobalComponents {
  'Test': typeof import("../../app/components/test.vue")['default']`

**Comment by Flo0806** [comment]
In my eyes .default is a standard and reserved keyword in javascript. Also it is fine. the `knitwork` 1.3.0 did the change. 
1. We can ask `knitwork` if they give us a special option to become `[default]` instead of .default.
2. Webstorm should fix this "issue", because it is correct javascript
3. We modify `Nuxt` to make this

2 should be the way I guess.

**Comment by cernymatej** [comment]
Agreed. This is something JetBrains should probably fix.

**Comment by yhagus** [comment]
Is this fixed yet in any WebStorm version?

**Comment by n0-m4d** [comment]
i stumbled upon the same issue and spent hours figuring out that downgrading from 4.2.2 to 4.2.1 fixes it. the latest phpstorm version still cant handle it.

**Comment by cernymatej** [comment]
Is there an open issue in YouTrack? If not, would you please open one? 🙏

**Comment by n0-m4d** [comment]
> Is there an open issue in YouTrack? If not, would you please open one? 🙏

https://youtrack.jetbrains.com/issue/WEB-76306/
